{% set name = "nr.stream" %}
{% set version = "1.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nr_stream-{{ version }}.tar.gz
  sha256: eb0216c6bfc61a46d4568dba3b588502c610ec8ddef4ac98f3932a2bd7264f65

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5,<4.0
  run:
    - nr.pylang.utils >=0.1.0,<1.0.0
    - python >=3.5,<4.0

test:
  imports:
    - nr
    - nr.stream
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://git.niklasrosenstein.com/NiklasRosenstein/nr
  summary: Use iterators like Java streams.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - NiklasRosenstein
