{% set name = "nr.stream" %}
{% set version = "0.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nr.stream-{{ version }}.tar.gz
  sha256: 76c93c8cc100b22d24fc4d751d35e8850f8094403f28c0862cb55a3644db6592

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - nr.pylang.utils >=0.1.0,<1.0.0
    - python >={{ python_min }},<4.0

test:
  imports:
    - nr
    - nr.stream
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://git.niklasrosenstein.com/NiklasRosenstein/nr
  summary: Use iterators like Java streams.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - NiklasRosenstein
